# Определение этапов (stages)
stages:
  - install
  - test

# Образ, внутри которого будут выполняться все команды
image: mcr.microsoft.com/playwright:v1.41.0-jammy

# Кэширование папки node_modules между запусками для ускорения
cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/

# Шаг 1: Установка зависимостей
install_dependencies:
  stage: install
  script:
    - npm ci

# Шаг 2: Запуск Smoke-тестов
run_smoke:
  stage: test
  script:
    # Запускаем тесты с твоим тегом. 
    # Кавычки здесь важны для Bash (внутри GitLab)
    - npx playwright test --grep "@smoke"
  artifacts:
    # Сохраняем отчеты, даже если тесты упали
    when: always
    paths:
      - playwright-report/
      - test-results/
    expire_in: 7 days
  # Ограничение: запускать только при пуше в ветку main или в Merge Request
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"