name: Playwright Tests
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      test_tag:
        description: 'Tag to run'
        default: '@smoke'
permissions:
  contents: write # Разрешение на создание и пуш в ветку gh-pages
  pages: write    # Разрешение на публикацию сайта
  id-token: write # Нужно для аутентификации деплоя
jobs:
  test:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2] # Разделение тестов на 2 параллельных потока
        shardTotal: [2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t pellu-tests .
      - name: Run Sharded Tests
        # Запуск тестов в контейнере с пробросом папки allure-results на хост
        run: |
          docker run --rm -v "${{ github.workspace }}/allure-results:/app/allure-results" pellu-tests /bin/bash -c "npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}"
      - name: Upload Shard Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results-shard-${{ matrix.shardIndex }}
          path: allure-results/
          retention-days: 1
  report_and_deploy:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download all shards
        uses: actions/download-artifact@v4
        with:
          path: all-results
          pattern: allure-results-shard-*
          merge-multiple: true
      # Используем git clone вместо checkout для надежности на любых раннерах
      - name: Get History
        run: |
          git clone --branch gh-pages --single-branch https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git old_report || true
          if [ -d "old_report/history" ]; then
            cp -r old_report/history all-results/
          fi
      - name: Generate Report
        run: |
          docker run --rm -v "$(pwd)/all-results:/app/allure-results" -v "$(pwd)/allure-report:/app/allure-report" frankescobar/allure-docker-service allure generate allure-results -o allure-report --clean
      # ПУШИМ В ВЕТКУ. После этого GitHub сам обновит сайт (если в настройках выбран Deploy from branch)
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages